name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Add Python setup
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # or whatever version you're using
          
      - name: Install dependencies
        run: make install
        
      - name: Lint and test
        run: |
          make lint
          make test
          make format